# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Live file tail (streaming).

Provides a Server-Sent Events (SSE) endpoint and a polling fallback that allow
a user to watch a file grow in real-time from the web UI (e.g. HPC job stdout).

Security model mirrors file_explorer.download():
  - @login_required + @feature_flag FILE_LIVE_TAIL (which depends on FILE_BROWSER)
  - File access mediated by an encrypted UID that carries file_owner and
    file_path (generated by file_explorer.encrypt())
  - check_user_permission() against Permissions.READ
  - current_user must match file_owner

Safety limits (all configurable via config.Config):
  - TAIL_MAX_FILE_SIZE
  - TAIL_MAX_CONCURRENT_PER_USER
  - TAIL_MAX_CONCURRENT_GLOBAL
  - TAIL_IDLE_TIMEOUT_SECONDS
  - TAIL_MAX_CONNECTION_SECONDS
  - TAIL_POLL_INTERVAL_MS
  - TAIL_INITIAL_TAIL_BYTES
  - TAIL_CHUNK_SIZE
"""
import json
import logging
import os
import stat
import threading
import time
from collections import defaultdict

from decorators import login_required, feature_flag
from flask import (
    Blueprint,
    Response,
    request,
    session,
    jsonify,
    stream_with_context,
    render_template,
)
from flask_babel import gettext as _
from utils.config import SocaConfig
from utils.validators import Validators, is_binary_file

# Reuse the shared UID-to-file resolver in file_explorer so tail and any
# future consumer (e.g. editor) authenticate file access identically.
from views.file_explorer import resolve_file

logger = logging.getLogger("soca_logger")
tail = Blueprint("tail", __name__, template_folder="templates")


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
# Values live in installer/default_config.yml under
# Config.web_interface.file_tail, are flattened into SSM parameter store at
# /configuration/WebInterface/file_tail/* during CDK deploy, and are read
# here via SocaConfig (which caches against Elasticache/Valkey, so this is
# cheap even for per-request reads).
#

def _tail_setting(key: str):
    """Read a tail setting from SSM with a fallback default.

    SocaConfig.get_value() returns a SocaResponse; the actual value lives
    in .message. We unwrap it here and coerce to the expected type. If the
    key is absent, a cast error occurs, or anything else goes wrong, we
    fall back to the hardcoded default so the view can't be broken by a
    misconfigured SSM tree.
    """
    _SSM_PREFIX = "/configuration/WebInterface/file_tail"
    _TAIL_KEYS = {
        # key_suffix: (return_as, default)
        "max_file_size":           (int, 1_073_741_824),  # 1 GB
        "max_concurrent_per_user": (int, 3),
        "max_concurrent_global":   (int, 50),
        "max_connection_seconds":  (int, 1800),           # 30 min
        "idle_timeout_seconds":    (int, 300),            # 5 min
        "poll_interval_ms":        (int, 500),
        "initial_tail_bytes":      (int, 65_536),         # 64 KB
        "chunk_size":              (int, 65_536),         # 64 KB
    }
    if key not in _TAIL_KEYS:
        raise KeyError(f"Unknown tail setting: {key}")
    return_as, default = _TAIL_KEYS[key]
    try:
        resp = SocaConfig(
            key=f"{_SSM_PREFIX}/{key}",
        ).get_value(
            return_as=return_as,
            default=default,
            allow_unknown_key=True,
        )
        # SocaResponse: prefer .message, fall back to dict-style access.
        raw = None
        if resp is None:
            raw = None
        elif hasattr(resp, "message"):
            raw = resp.message
        elif Validators.is_dict(resp):
            raw = resp.get("message")
        else:
            raw = resp
        if raw is None or raw == "":
            return default
        # Defensive cast: SSM parameters are stringly-typed even when we
        # ask for int via return_as.
        try:
            return return_as(raw)
        except (TypeError, ValueError):
            return default
    except Exception as err:
        logger.warning("tail: config read failed for %s (%s); using default %r",
                       key, err, default)
        return default


def _sse_error_response(message: str):
    """
    Build a one-shot SSE response carrying a single `error` event.

    EventSource clients have no "why did this fail?" introspection, so the
    convention in this module is: when the request fails *before* we've
    started streaming, send a well-formed SSE frame with event=error and
    a human-readable message, then close. That lets the viewer show a
    friendly message rather than a cryptic network error.

    The payload is built as a plain string and passed straight to
    Response(); no generator wrapper is needed because the payload is
    known up front and is emitted in a single chunk.
    """
    payload = f"event: error\ndata: {json.dumps({'message': message})}\n\n"
    return Response(payload, mimetype="text/event-stream")


# ---------------------------------------------------------------------------
# Concurrency tracking
# ---------------------------------------------------------------------------
# Simple in-process counters. Because uWSGI runs multiple processes, these
# counts are per-process, not per-cluster. That's acceptable for a soft cap —
# the real hard limits are the OS-level fd/thread limits. If we ever need a
# cluster-wide limit we can back this by Redis/Elasticache (already used by
# SOCA for other shared state), but that is out of scope for the MVP.
_active_tails_lock = threading.Lock()
_active_tails_by_user: dict = defaultdict(int)
_active_tails_global: int = 0


def _acquire_slot(user: str) -> bool:
    global _active_tails_global
    max_global = _tail_setting("max_concurrent_global")
    max_per_user = _tail_setting("max_concurrent_per_user")
    with _active_tails_lock:
        if _active_tails_global >= max_global:
            return False
        if _active_tails_by_user[user] >= max_per_user:
            return False
        _active_tails_by_user[user] += 1
        _active_tails_global += 1
        return True
    # Not Reached
    return False


def _release_slot(user: str) -> None:
    global _active_tails_global
    with _active_tails_lock:
        _active_tails_by_user[user] = max(0, _active_tails_by_user[user] - 1)
        _active_tails_global = max(0, _active_tails_global - 1)


# ---------------------------------------------------------------------------
# File resolution (shared by SSE + poll endpoints)
# ---------------------------------------------------------------------------
def _resolve_file(uid: str):
    """
    Thin wrapper around views.file_explorer.resolve_file() that layers the
    tail-specific size cap on top of the shared UID -> file lookup.

    The shared helper handles UID decrypt, ownership verification, read-
    permission check and regular-file check. We then enforce the tail
    "max_file_size" setting on the returned size with a user-facing
    message that nudges the user toward download for oversized files.

    Returns (info, None) on success or (None, error_message) on failure.
    """
    file_info, err = resolve_file(uid)
    if err:
        return None, err
    max_file_size = _tail_setting("max_file_size")
    if file_info["size"] > max_file_size:
        return None, _(
            "File is too large to tail (max {max_mb:.0f} MB). Use download instead."
        ).format(max_mb=max_file_size / 1024 / 1024)
    return file_info, None


# ---------------------------------------------------------------------------
# SSE streaming endpoint
# ---------------------------------------------------------------------------
@tail.route("/file_explorer/tail/stream", methods=["GET"])
@login_required
@feature_flag(flag_name="FILE_LIVE_TAIL", mode="view")
def stream():
    uid = request.args.get("uid")

    file_info, err = _resolve_file(uid)
    if err:
        return _sse_error_response(err)

    if is_binary_file(file_info["path"]):
        return _sse_error_response(
            _("File appears to be binary and cannot be tailed")
        )

    current_user = session["user"]
    if not _acquire_slot(current_user):
        return _sse_error_response(
            _("Too many active tail sessions. Close one and try again.")
        )

    file_path = file_info["path"]
    file_size = file_info["size"]

    poll_interval = _tail_setting("poll_interval_ms") / 1000.0
    max_duration = _tail_setting("max_connection_seconds")
    idle_timeout = _tail_setting("idle_timeout_seconds")
    chunk_size = _tail_setting("chunk_size")
    initial_bytes = _tail_setting("initial_tail_bytes")

    def generate():
        start_time = time.monotonic()
        last_activity = start_time
        fh = None
        try:
            # Atomic open; O_NOFOLLOW refuses a symlink swapped in after the permission check, O_NONBLOCK avoids a FIFO block (uwsgi runs as root).
            _fd = os.open(file_path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
            if not stat.S_ISREG(os.fstat(_fd).st_mode):
                os.close(_fd)
                logger.warning("tail: refusing non-regular file at %s", file_path)
                yield "event: error\ndata: " + json.dumps({"error": "Unable to read file"}) + "\n\n"
                return
            fh = os.fdopen(_fd, "rb")
            # Start from end - initial_bytes so the user sees recent context
            # (like `tail -c N`) rather than the whole history.
            start_offset = max(0, file_size - initial_bytes)
            fh.seek(start_offset)

            current_inode = os.fstat(fh.fileno()).st_ino

            # Announce start with metadata (useful for the client UI).
            yield (
                "event: start\n"
                "data: " + json.dumps({
                    "path": file_path,
                    "size": file_size,
                    "offset": start_offset,
                    "inode": current_inode,
                    "poll_ms": int(poll_interval * 1000),
                }) + "\n\n"
            )

            while True:
                now = time.monotonic()
                if now - start_time > max_duration:
                    yield (
                        "event: done\n"
                        "data: " + json.dumps({"reason": "max_duration"}) + "\n\n"
                    )
                    return
                if now - last_activity > idle_timeout:
                    yield (
                        "event: done\n"
                        "data: " + json.dumps({"reason": "idle_timeout"}) + "\n\n"
                    )
                    return

                chunk = fh.read(chunk_size)
                if chunk:
                    last_activity = now
                    # SSE requires each line of `data:` to be prefixed. We
                    # encode the raw bytes as a JSON string so newlines inside
                    # the log content don't break the SSE frame.
                    try:
                        text = chunk.decode("utf-8", errors="replace")
                    except UnicodeDecodeError as _err:
                        logger.debug(
                            "tail: utf-8 decode fell back to latin-1 on %s: %s",
                            file_path, _err,
                        )
                        text = chunk.decode("latin-1", errors="replace")
                    yield (
                        "event: data\n"
                        "data: " + json.dumps({"text": text}) + "\n\n"
                    )
                else:
                    # No new data. Check for rotation/truncation.
                    try:
                        st = os.stat(file_path)
                        if st.st_ino != current_inode:
                            yield (
                                "event: rotated\n"
                                "data: " + json.dumps({
                                    "message": _("File rotated"),
                                }) + "\n\n"
                            )
                            return
                        if st.st_size < fh.tell():
                            # Truncation: seek to 0 and tell client.
                            fh.seek(0)
                            yield (
                                "event: truncated\n"
                                "data: " + json.dumps({
                                    "message": _("File truncated"),
                                }) + "\n\n"
                            )
                    except OSError as _err:
                        logger.warning(
                            "tail: stat() failed during stream of %s: %s",
                            file_path, _err,
                        )
                        yield (
                            "event: done\n"
                            "data: " + json.dumps({"reason": "stat_error"}) + "\n\n"
                        )
                        return

                    # Heartbeat comment every poll so proxies (ALB, uWSGI) see
                    # traffic and don't close the connection.
                    yield ": hb\n\n"
                    time.sleep(poll_interval)
        except GeneratorExit:
            # Client disconnected.
            logger.debug("tail: client disconnected for %s", file_path)
        except Exception as _err:
            logger.warning("tail: streaming error on %s: %s", file_path, _err)
            try:
                yield (
                    "event: error\n"
                    "data: " + json.dumps({"message": str(_err)}) + "\n\n"
                )
            except Exception as deliver_err:
                # Client likely already closed the SSE connection, so we
                # can't tell them about the original error. Logged at debug
                # because this is expected on graceful disconnect races.
                logger.debug(
                    "tail: could not deliver error event to client (%s): %s",
                    file_path, deliver_err,
                )
        finally:
            try:
                if fh is not None:
                    fh.close()
            except Exception as close_err:
                # Close failures after a stream finishes are benign in
                # practice (fd was already reclaimed by the OS on client
                # disconnect, etc.) but worth a debug breadcrumb in case
                # they correlate with fd-leak alarms.
                logger.debug(
                    "tail: fh.close() failed on %s: %s",
                    file_path, close_err,
                )
            _release_slot(current_user)

    resp = Response(
        stream_with_context(generate()),
        mimetype="text/event-stream",
    )
    # Disable buffering at every layer we can reach.
    resp.headers["Cache-Control"] = "no-cache, no-transform"
    resp.headers["X-Accel-Buffering"] = "no"
    resp.headers["Connection"] = "keep-alive"
    return resp


# ---------------------------------------------------------------------------
# Polling fallback endpoint
# ---------------------------------------------------------------------------
@tail.route("/file_explorer/tail/poll", methods=["GET"])
@login_required
@feature_flag(flag_name="FILE_LIVE_TAIL", mode="view")
def poll():
    """
    JSON polling fallback for environments where SSE is blocked or where the
    client prefers to have explicit control over fetch cadence. Returns up to
    TAIL_CHUNK_SIZE bytes starting at `offset`, plus the new offset and size.

    Query params:
      - uid: encrypted file identifier (same as SSE)
      - offset: byte offset to resume from (0 to start with last N bytes)
      - max_bytes: optional, capped by TAIL_CHUNK_SIZE
    """
    uid = request.args.get("uid")
    try:
        offset = int(request.args.get("offset", "-1"))
    except ValueError:
        offset = -1
    chunk_size = _tail_setting("chunk_size")
    try:
        max_bytes = int(request.args.get("max_bytes", chunk_size))
    except ValueError:
        max_bytes = chunk_size
    max_bytes = min(max_bytes, chunk_size)

    file_info, err = _resolve_file(uid)
    if err:
        return jsonify(success=False, message=err), 400

    if is_binary_file(file_info["path"]):
        return jsonify(
            success=False,
            message=_("File appears to be binary and cannot be tailed"),
        ), 400

    file_path = file_info["path"]
    file_size = file_info["size"]
    align_newline = request.args.get("align") == "newline"

    # offset == -1 (default) means "start from recent tail"
    if offset < 0:
        offset = max(0, file_size - _tail_setting("initial_tail_bytes"))

    if offset > file_size:
        # Probably truncated. Reset.
        offset = 0

    try:
        # Atomic open; O_NOFOLLOW refuses a symlink swapped in after the permission check, O_NONBLOCK avoids a FIFO block (uwsgi runs as root).
        _fd = os.open(file_path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
        if not stat.S_ISREG(os.fstat(_fd).st_mode):
            os.close(_fd)
            logger.warning("tail: poll refusing non-regular file at %s", file_path)
            return jsonify(success=False, message=_("Unable to read file")), 500
        with os.fdopen(_fd, "rb") as fh:
            inode = os.fstat(fh.fileno()).st_ino
            fh.seek(offset)
            chunk = fh.read(max_bytes)
    except OSError as err:
        logger.warning("tail: poll read failed on %s: %s", file_path, err)
        return jsonify(success=False, message=_("Unable to read file")), 500

    start_offset = offset

    # When back-loading, the first line is almost always truncated because
    # we seeked to an arbitrary byte. Trim up to the first newline so the
    # caller can safely prepend the chunk without half-lines showing up.
    # Also protects against splitting a multi-byte UTF-8 sequence.
    if align_newline and start_offset > 0 and chunk:
        nl = chunk.find(b"\n")
        if 0 <= nl < len(chunk) - 1:
            chunk = chunk[nl + 1:]
            start_offset += nl + 1

    try:
        text = chunk.decode("utf-8", errors="replace")
    except UnicodeDecodeError as err:
        logger.debug(
            "tail: utf-8 decode fell back to latin-1 on %s: %s",
            file_path, err,
        )
        text = chunk.decode("latin-1", errors="replace")

    end_offset = start_offset + len(chunk)
    return jsonify(
        success=True,
        path=file_path,
        start_offset=start_offset,
        offset=end_offset,       # kept for backwards compat with any existing caller
        end_offset=end_offset,
        size=file_size,
        inode=inode,
        eof=(end_offset >= file_size),
        text=text,
    )


# ---------------------------------------------------------------------------
# Standalone pop-out view
# ---------------------------------------------------------------------------
@tail.route("/file_explorer/tail/view", methods=["GET"])
@login_required
@feature_flag(flag_name="FILE_LIVE_TAIL", mode="view")
def view():
    """
    Full-page tail viewer intended to be opened in a separate browser window.
    The UID is validated server-side before rendering so an unauthorized or
    malformed token fails fast with a visible message rather than silently
    hanging on the SSE connection.

    Client JS in tail_viewer.html auto-starts the stream from ?uid=... when
    tail_standalone is set in the template context.
    """
    uid = request.args.get("uid", "")
    name = request.args.get("name", "")

    # Validate before rendering so we never open a pop-out that would fail
    # on the stream endpoint anyway.
    file_info, err = _resolve_file(uid)
    if err:
        # Render the page with a pre-populated error rather than a blank
        # viewer; the auto-start JS will see no uid and show the error.
        return render_template(
            "tail_page.html",
            uid="",
            display_name="",
            initial_error=err,
        )

    # Prefer the real filename if the caller didn't supply one.
    if not name:
        name = os.path.basename(file_info["path"])

    return render_template(
        "tail_page.html",
        uid=uid,
        display_name=name,
    )
